baseURL: http://example.org/                  # Hosting location.
languageCode: en-us                           # Locale
title: Acme Corporation                       # Name of the website
theme: acme                                   # Name of the theme
enableEmoji: true                             # Enable Emoticons
enableGitInfo: true                           # Allow access to Git data
Paginate: 3                                   # 3 Posts per page
