baseURL: http://example.org/                  # Hosting location.
languageCode: en-us                           # Locale
title: Acme Corporation                       # Name of the website
theme: acme                                   # Name of the theme
enableEmoji: true                             # Enable Emojis
markup:                                       # Markup Options
  highlight:                                  # Code highlighting defaults
    lineNos: true                             # Enable line numbers
